server:
  port: 8001

mybatis:
  mapper-locations: classpath:com/bjb/dao/mapper/*.xml

spring:
  application:
    name: springcloud-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/own_mysql?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password:

#Eureka的配置，注册服务地址
eureka:
  client:
    register-with-eureka: true #是否将自己注册到注册中心上
    fetch-registry: true #是否从Eureka上获取注册信息
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-8001 #修改Eureka上的默认描述信息
#    prefer-ip-address: true #使用ip进行注册
#  server:
#    eviction-interval-timer-in-ms: 20000 #服务剔除间隔
#    enable-self-preservation: false #关闭自我保护机制(不推荐使用)

#info配置
info:
  app.name: springcloud-study
  company.name: blog.xustudy.com